# On Heroku and other platform providers, you may have a full connection URL
# available as an environment variable. For example:
#
#   DATABASE_URL="postgres://myuser:mypass@localhost/somedatabase"
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  port: 5432

development:
  <<: *default
  username: postgres
  database: campo_development

test:
  <<: *default
  username: postgres
  database: campo_test

production:
  <<: *default
  username: deploy
  password: <%= ENV['POSTGRESQL_PASSWORD'] %>
  database: campo_production
